defaults: &defaults
  working_directory: ~/exodus
  docker:
    - image: circleci/python:3.6.1


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "development-requirements.txt" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip install -r development-requirements.txt
            sudo apt-get install gcc musl musl-tools patchelf python-dev strace
      - save_cache:
          paths:
            - ./.env
          key: v1-dependencies-{{ arch }}-{{ .Branch }}-{{ checksum "development-requirements.txt" }}

      - run:
          name: Run the tests.
          command: |
            . .env/bin/activate
            tox
            echo "{ \"coverage\": \"$(coverage report | tail -n 1 | awk '{print $6}')\" }" > htmlcov/total-coverage.json

      - run:
          name: Build the package.
          command: |
            python setup.py sdist bdist_wheel

      - run:
          name: Build Self-Hosted Bundle
          command: |
            . .env/bin/activate
            pip install .
            (cat <<EOF > ./exodus.c
            #include <libgen.h>
            #include <stdlib.h>
            #include <string.h>
            #include <unistd.h>

            int main(int argc, char *argv[]) {
                char buffer[4096] = { 0 };
                if (readlink("/proc/self/exe", buffer, sizeof(buffer) - 25)) {
                    char *current_directory = dirname(buffer);
                    int current_directory_length = strlen(current_directory);

                    char python[4096] = { 0 };
                    strcpy(python, current_directory);
                    strcat(python, "/.env/bin/python");

                    char exodus[4096] = { 0 };
                    strcpy(exodus, current_directory);
                    strcat(exodus, "/.env/bin/exodus");

                    char **combined_args = malloc(sizeof(char*) * (argc + 2));
                    combined_args[0] = python;
                    combined_args[1] = exodus;
                    memcpy(combined_args + 2, argv + 1, sizeof(char*) * (argc - 1));
                    combined_args[argc + 1] = NULL;

                    execv(python, combined_args);
                }

                return 1;
            }
            EOF
            )
            musl-gcc -static -O3 exodus.c -o exodus
            export LD_LIBRARY_PATH=/usr/local/lib/:/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}
            strace ./exodus -q gcc 2>&1 | ./exodus ./exodus --add .env/lib/python*/site-packages/exodus_bundler/ --tar --output exodus-x64.tgz
            strace exodus -q gcc 2>&1 | exodus exodus --add .env/lib/python*/site-packages/exodus_bundler/ --output exodus-x64.sh
      - store_artifacts:
          path: htmlcov
          destination: coverage-report
      - store_artifacts:
          path: exodus-x64.sh
          destination: exodus-x64.sh
      - store_artifacts:
          path: exodus-x64.tgz
          destination: exodus-x64.tgz

      - persist_to_workspace:
          root: ~/exodus
          paths:
            - .env
            - dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/exodus
      - run:
          name: Upload package to PyPI.
          command: |
            . .env/bin/activate
            twine upload --skip-existing dist/*


workflows:
  version: 2

  build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /v[0-9]+(\.[0-9]+)*/

  release:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
          requires:
            - build
